# Generated by Django 4.2.3 on 2023-07-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pastryrecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('preptime', models.IntegerField()),
                ('cookingtime', models.IntegerField()),
                ('totaltime', models.IntegerField()),
                ('yields', models.IntegerField()),
                ('instructions', models.TextField()),
                ('ingredients', models.TextField()),
            ],
        ),
    ]
