# Generated by Django 4.2.3 on 2023-07-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastryrecipe',
            name='photo',
            field=models.ImageField(blank=True, upload_to='recipes/'),
        ),
    ]
