# Generated by Django 4.2.3 on 2023-07-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_pastryrecipe_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastryrecipe',
            name='img',
            field=models.ImageField(blank=True, upload_to='recipes/'),
        ),
    ]
