# Generated by Django 4.2.3 on 2023-07-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_category_pastryrecipe_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='pastryrecipe',
            name='category',
        ),
    ]
