# Generated by Django 4.2.3 on 2023-07-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_delete_category_remove_pastryrecipe_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='No Image', upload_to='recipes/'),
        ),
    ]
