# Generated by Django 4.2.3 on 2023-07-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_photo_url_photo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='url',
        ),
    ]
