# Generated by Django 4.2.3 on 2023-07-17 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_image_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastryrecipe',
            name='img',
        ),
    ]
