# Generated by Django 4.2.3 on 2023-07-17 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_pastryrecipe_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CC', 'Cakes and Cupcakes'), ('PT', 'Pies and Tarts'), ('CB', 'Cookies and Bisquits'), ('PP', 'Pastries and Puff Pastry'), ('FD', 'Frozen Desserts'), ('PC', 'Puddings and Custards'), ('FR', 'Fruit-based Desserts'), ('ID', 'International Desserts'), ('OT', 'Other Desserts')], default='CC', max_length=200)),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pastryrecipe')),
            ],
        ),
    ]
