# Generated by Django 4.2.3 on 2023-07-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('CC', 'Cakes and Cupcakes'), ('PT', 'Pies and Tarts'), ('CB', 'Cookies and Bisquits'), ('PP', 'Pastries and Puff Pastry'), ('FD', 'Frozen Desserts'), ('PC', 'Puddings and Custards'), ('FR', 'Fruit-based Desserts'), ('ID', 'International Desserts'), ('OT', 'Other Desserts')], default='Cakes and Cupcakes', max_length=4),
        ),
    ]
