# Generated by Django 4.2.3 on 2023-07-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastryrecipe',
            name='categorytype',
            field=models.CharField(choices=[('CC', 'Cakes and Cupcakes'), ('PT', 'Pies and Tarts'), ('CB', 'Cookies and Bisquits'), ('PP', 'Pastries and Puff Pastry'), ('FD', 'Frozen Desserts'), ('PC', 'Puddings and Custards'), ('FR', 'Fruit-based Desserts'), ('ID', 'International Desserts'), ('OT', 'Other Desserts')], default='CC', max_length=2, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='pastryrecipe',
            name='cookingtime',
            field=models.IntegerField(verbose_name='Cooking Time'),
        ),
        migrations.AlterField(
            model_name='pastryrecipe',
            name='ingredients',
            field=models.TextField(verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='pastryrecipe',
            name='instructions',
            field=models.TextField(verbose_name='Instructions'),
        ),
        migrations.AlterField(
            model_name='pastryrecipe',
            name='preptime',
            field=models.IntegerField(verbose_name='Prep Time'),
        ),
        migrations.AlterField(
            model_name='pastryrecipe',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='pastryrecipe',
            name='totaltime',
            field=models.IntegerField(verbose_name='Total Time'),
        ),
        migrations.AlterField(
            model_name='pastryrecipe',
            name='yields',
            field=models.IntegerField(verbose_name='Yields'),
        ),
    ]
