# Generated by Django 4.2.3 on 2023-07-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_pastryrecipe_categorytype_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastryrecipe',
            name='categorytype',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
